CR EQU 0C6H
PA EQU 0C0H
PB EQU 0C2H
TABLE DB 6DH, 3EH, 58H, 58H, 7BH, 6DH, 6DH
MOV AL, 80H
OUT CR, AL
START: LEA SI, TABLE
       MOV CX, 7H
       MOV BL, 01111111
AGN: MOV AL, BL
     OUT PA, AL
     MOV AL, [SI]
     OUT PB, AL
CALL DELAY
INC SI
ROR BL, 1
LOOP AGN
JMP START
DELAY PROC NEAR 
MOV DX, 300
BACK: DEC DX
JNZ BACK
RET
DELAY ENDP
END